### ISSUE TITLE
tweepy실행이 되지 않습니다.

### ISSUE THREAD

**Issue by nikon5100** [hcid-courses/datajournalism-2018#19]
### 실행 환경

- windows8 + 32bits + 8GB / Python **3.7.1** version, IDE or Editor, etc

### 문제 상황

수업시간에서부터 지금까지 week12를 아무것도 하지 못하고 있습니다. 첫째줄에 있는 tweepy만해도 오류가 발생합니다.

### 에러 메시지
Traceback (most recent call last):

  File "c:\users\jy_2\appdata\local\programs\python\python37-32\lib\sitepackages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-13-2237e5ac034b>", line 1, in <module>
    import tweepy

  File "c:\users\jy_2\appdata\local\programs\python\python37-32\lib\site-packages\tweepy\__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener

  File "c:\users\jy_2\appdata\local\programs\python\python37-32\lib\site-packages\tweepy\streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax

### 스크린샷

![image](https://user-images.githubusercontent.com/43132451/48968687-4ae19c80-f036-11e8-8a0a-7d5c2c124873.png)

**Comment by nikon5100** [comment]
python 호환성 문제인 것을 확인하고 해결했습니다. 감사합니다.
