### ISSUE TITLE
인증키 오류

### ISSUE THREAD

**Issue by fiktionen** [hcid-courses/datajournalism-2018#22]
### 실행 환경

- macOS High Sierra + 64bits + 8GB, Python **3.5** version, PyCharm 

### 코드 

*코드 파일 전체를 올리지 말고, 에러가 일어난 라인 및 의존성이 있는 부분(import package, 사용한 변수의 선언 등)만 올려주세요*

```python
# 
def fine_dust_fetch(self, region=None):
        self.county = region

        app_key = ""
        loc = "관악구"
        url = "http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty?stationName={}&dataTerm=month&pageNo=1&numOfRows=1&ServiceKey={}&ver=1.3&_returnType=json".format(
            parse.quote(loc), app_key)

        with urllib.request.urlopen(url) as response:
            self.fine_dust_data = json.loads(response.read().decode("utf-8"))

        return self.fine_dust_data

# ex)
from datetime import datetime, date, time
datetime.now().strftime('%Y년 %-d월 %-m일')
```

### 설명

공공데이터 포털에서 미세먼지 정보를 긁어오는 코드입니다.
인증키 부분을 제외하고는 주신 코드와 거의 동일한데
사이트에서 승인이 되었음에도 불구하고 인증키 거절 오류가 발생합니다. 
혹시 몰라서 재발급도 받아보았고 재발급받은지 하루가 다되어가는데 아직도 오류가 발생하고 있습니다.
(loc="관악구"로 별도 설정한 이유는 앞의 날씨 크롤러가 region이 아닌  lat, lon으로 받아오는 구조라서입니다)

그래서 제 인증키를 넣었을 경우 url에서 json데이터가 아닌 오류메세지가 출력되어서
파이썬에서 jsonDecodeError가 발생합니다.

인증키는 메일로 별도로 보내드렸습니다. 

### 에러 메시지

*에러 메시지를 복붙해주세요. 필요하면 특별히 에러가 나는 상황도 설명해주세요.*

```
#
Traceback (most recent call last):
  File "/Users/ficciones/datajournalism-2018/lab-codes/Week13/robot_journalism_lab/rj_app.py", line 14, in <module>
    fine_dust_data = crawler.fine_dust_fetch("관악구")
  File "/Users/ficciones/datajournalism-2018/lab-codes/Week13/robot_journalism_lab/crawler.py", line 43, in fine_dust_fetch
    self.fine_dust_data = json.loads(response.read().decode("utf-8"))
  File "/Users/ficciones/anaconda3/envs/tutorial/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Users/ficciones/anaconda3/envs/tutorial/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ficciones/anaconda3/envs/tutorial/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

# ex)
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-1-efd39827dcf5> in <module>()
      1 from datetime import datetime, date, time
      2 
----> 3 datetime.now().strftime('%Y년 %-d월 %-m일')

UnicodeEncodeError: 'locale' codec can't encode character '\ub144' in position 2: Illegal byte sequence
```

**Comment by see-mike-out** [comment]
자세히 알아보니, 해당 장애가 비교적 빈번히 발생하는 것 같습니다. http://bit.ly/airkoreaqna 이런 링크를 한국환경공단에서 제공하고 있으니, 문의를 남겨 키가 제대로 작동할 수 있도록 확인하길 바랍니다. 이 작업은 다소 시일이 걸릴 수 있습니다. 과제 마감인 10일까지 문제 해결이 어렵다고 생각하는 다른 학생들도 저에게 메일 주면 임시로 활용가능한 API키를 드리겠습니다 (과제 채점 해당 키는 모두 제거 예정).

**Comment by yuyupopo** [comment]
해당 장애가 빈번비 발생한다면, 과제에는 해당 api를 사용하지 않아도 무방한가요?

**Comment by see-mike-out** [comment]
이번 과제의 목표가 날씨기사를 작성하는 것이기 때문에 가급적 airkorea api를 활용하기를 바랍니다.

**Comment by monot** [comment]
날씨를 가져오는 다른 API 를 써도 괜찮을 것 같습니다.
