### ISSUE TITLE
json 파일 인코딩 문제

### ISSUE THREAD

**Issue by wltjd54** [hcid-courses/datajournalism-2018#23]
### 실행 환경

- OS + bits + RAM, Python **specific** version, IDE or Editor, 
- Windows10 + 64bit + 8GB / Python **3.6.5** / PyCharm

### 코드

*코드 파일 전체를 올리지 말고, 에러가 일어난 라인 및 의존성이 있는 부분(import package, 사용한 변수의 선언 등)만 올려주세요*  

```python
# put your code segment here..
<crawler.py>

    def fine_dust_fetch(self, region=None):
        self.county = region

        app_key = ""
        loc = self.county
        url = "http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty?stationName={}&dataTerm=month&pageNo=1&numOfRows=1&ServiceKey={}&ver=1.3&_returnType=json".format(
            parse.quote(loc), app_key)
        # print(url) # check REST url

        with urllib.request.urlopen(url) as response:
            self.fine_dust_data = json.loads(response.read().decode("utf-8"))

        return self.fine_dust_data

<rj_app.py>

weather_data = crawler.weather_fetch("Busan")
fine_dust_data = crawler.fine_dust_fetch("연산동")

```
### 설명

*작성한 코드의 목적과 내용을 최대한 자세하게 논리적으로 설명해주세요.*

현재 appkey는 정상적으로 넣었는데 json으로 변환하는 과정에서 디코드에러가 발생합니다..

### 에러 메시지

*에러 메시지를 복붙해주세요. 필요하면 특별히 에러가 나는 상황도 설명해주세요.*

```
# copy & paste your error message here..

# ex)
Traceback (most recent call last):
  File "C:/Users/wltjd/Desktop/Computer/PyCharm/venv/robot_journalism_lab/rj_app.py", line 10, in <module>
    fine_dust_data = crawler.fine_dust_fetch("연산동")
  File "C:\Users\wltjd\Desktop\Computer\PyCharm\venv\robot_journalism_lab\crawler.py", line 33, in fine_dust_fetch
    self.fine_dust_data = json.loads(response.read().decode("utf-8"))
  File "C:\Users\wltjd\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\wltjd\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\wltjd\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by drater05** [comment]
#22
